version: 0.2

phases:
    install:
        commands:
        - dotnet tool install -g Microsoft.Web.LibraryManager.Cli
    build:
        commands:
        - mkdir -p build/publish
        - echo "Building with dotnet SDK Version $(dotnet --version)"
        - |
          pushd BeanstalkExample.Core
          libman restore
          dotnet publish -c Release -o ../build/publish
          popd
        - echo "Build completed."
    # Prepare for CodeDeploy deployment
        - |
          if [$TARGET_OS -eq "windows"]; then 
            cp -r codedeploy/windows/appspec.yml build/
          else
            cp -r codedeploy/linux/appspec.yml build/
          fi
artifacts:
    files: [ '**/*' ]
    name: PublishedBinaries
    base-directory: build
