version: 0.2

phases:
    install:
        commands:
        - dotnet tool install -g Microsoft.Web.LibraryManager.Cli
    build:
        commands:
        - mkdir -p build/publish
        - pushd BeanstalkExample.Core
        - libman restore
        - echo "Building with dotnet SDK Version $(dotnet --version)"
        - dotnet publish -c Release -o ../build/publish
        - echo "Build completed."
        - popd
    # Prepare for CodeDeploy deployment
        - cp src/codedeploy/appSpec.yml build/
artifacts:
    files: [ 'build/publish/**/*' ]
    name: PublishedBinaries
    base-directory: build/publish
