version: 0.2

phases:
    install:
        commands:
        - dotnet tool install -g Microsoft.Web.LibraryManager.Cli
    build:
        commands:
        - mkdir -p build/publish
        - echo "Building with dotnet SDK Version $(dotnet --version)"
        - |
          pushd BeanstalkExample.Core
          libman restore
          dotnet publish -c Release -o ../build/publish
          popd
        - echo "Build completed."
    # Prepare for CodeDeploy deployment
        - cp src/codedeploy/appSpec.yml build/
artifacts:
    files: [ 'build/publish/**/*' ]
    name: PublishedBinaries
    base-directory: build/publish
